# Generated by Django 5.0.1 on 2024-01-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='body',
            field=models.TextField(default='My name is Daniel'),
            preserve_default=False,
        ),
    ]
