# Generated by Django 5.0.1 on 2024-01-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_alter_aboutus_body_alter_category_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='snippet',
            field=models.CharField(default='Click Link Above To Lead Blog Post...', max_length=255),
        ),
    ]
