# Generated by Django 5.0.1 on 2024-02-02 02:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_category_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='snippet',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
