# Generated by Django 5.0.1 on 2024-02-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_post_image2_post_image3_post_image4_post_image5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='advert',
            field=models.TextField(default='This is the value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='This is the value'),
            preserve_default=False,
        ),
    ]
